ALTER SESSION set NLS_DATE_FORMAT = 'yyyy-mm-dd HH24:MI:SS';

DROP TABLE DRIVES CASCADE CONSTRAINTS;
DROP TABLE PRICE CASCADE CONSTRAINTS;
DROP TABLE RESERVATION CASCADE CONSTRAINTS;

DROP table SEAT CASCADE CONSTRAINTS;
DROP table ACCOUNT CASCADE CONSTRAINTS;
DROP table TIMETABLE CASCADE CONSTRAINTS;

drop table BUS CASCADE CONSTRAINTS;
drop table ROUTE CASCADE CONSTRAINTS;
drop table EMPLOYEE CASCADE CONSTRAINTS;

drop table STATION CASCADE CONSTRAINTS;

CREATE TABLE ACCOUNT(
    Aid CHAR(9) NOT NULL,
    Fname VARCHAR(15) NOT NULL,
    Lname VARCHAR(15) NOT NULL,
    Email VARCHAR(30) NOT NULL,
    PW VARCHAR(15) NOT NULL,
    Phone CHAR(11),
    Point NUMBER,
    PRIMARY KEY(Aid)
);

CREATE TABLE SEAT(
    Sid CHAR(2) NOT NULL,
    Rownumber CHAR(1) NOT NULL,
    Colnumber CHAR(1) NOT NULL,
    PRIMARY KEY (Sid)
);

CREATE TABLE STATION(
    STname VARCHAR(30) NOT NULL,
    TotalPlatform NUMBER,
    Address VARCHAR(150) NOT NULL,
    Zipcode CHAR(5),
    PRIMARY KEY (STname)
);

CREATE TABLE ROUTE(
    Rid NUMBER NOT NULL,
    Dstation VARCHAR(30) NOT NULL,
    Astation VARCHAR(30) NOT NULL,
    Dplatform NUMBER NOT NULL,
    Aplatform NUMBER NOT NULL,
    PRIMARY KEY (Rid),
    FOREIGN KEY (Dstation) REFERENCES STATION(STname),
    FOREIGN KEY (Astation) REFERENCES STATION(STname)
);

CREATE TABLE PRICE(
    Age VARCHAR(30) NOT NULL,
    BusType VARCHAR(30) NOT NULL,
    Fee NUMBER NOT NULL,
    PRid NUMBER NOT NULL,
    PRIMARY KEY (BusType, Age, PRid),
    FOREIGN KEY (PRid) REFERENCES ROUTE(Rid)
);

CREATE TABLE BUS(
    Bid CHAR(4) NOT NULL,
    Bcompany VARCHAR(30) NOT NULL,
    Btype VARCHAR(10) NOT NULL,
    PRIMARY KEY (Bid)
);

CREATE TABLE TIMETABLE(
    Tid NUMBER NOT NULL,
    TDate DATE NOT NULL,
    Depart_time TIMESTAMP NOT NULL,
    Arrive_time TIMESTAMP NOT NULL,
    TBid CHAR(4) NOT NULL,
    TRid NUMBER NOT NULL,
    PRIMARY KEY (Tid),
    FOREIGN KEY (TBid) REFERENCES BUS(Bid),
    FOREIGN KEY (TRid) REFERENCES ROUTE(Rid)
);

CREATE TABLE RESERVATION(
    RAid CHAR(9) NOT NULL,
    RSid CHAR(2) NOT NULL,
    RTid NUMBER NOT NULL,
    PRIMARY KEY (RSid, RTid),
    FOREIGN KEY (RAid) REFERENCES ACCOUNT(Aid),
    FOREIGN KEY (RSid) REFERENCES SEAT(Sid),
    FOREIGN KEY (RTid) REFERENCES TIMETABLE(Tid)
);

CREATE TABLE EMPLOYEE(
    Ssn CHAR(9) NOT NULL,
    Fname VARCHAR(30) NOT NULL,
    Lname VARCHAR(30) NOT NULL,
    Salary NUMBER,
    ESname VARCHAR(30),
    PRIMARY KEY (Ssn),
    FOREIGN KEY (ESname) REFERENCES Station(STname)
);

CREATE TABLE DRIVES(
    DBid CHAR(4) NOT NULL,
    DSsn CHAR(9) NOT NULL,
    Hours NUMBER(4,1),
    PRIMARY KEY (DBid, DSsn),
    FOREIGN KEY (DBid) REFERENCES BUS(Bid),
    FOREIGN KEY (DSsn) REFERENCES EMPLOYEE(Ssn)
);

commit;